baseURL       : "https://adityam.github.io/context-blog"

languageCode  : "en-us"
title         : A Blog about ConTeXt
author        : Aditya Mahajan
theme         : homepage

metaDataFormat: yaml
publishDir    : docs

rssLimit      : 10

params:
  disqus : "random-determinism"

    # markup:
    #   defaultMarkdownHandler: "blackfriday"

markup:
  goldmark:
    renderer:
      unsafe: true

